### PR TITLE
Fixes NO_LOGIN after adding ECR support

### PR DESCRIPTION
**Pull request by mbentley**
Signed-off-by: Matt Bentley <matt.bentley@docker.com>

### CODE REVIEW

**Comment by mbentley** [comment]
@mattnowina - Could you check this to make sure it does not break ECR support?  I changed the environment variables that were ECR specific and made this work with the existing naming scheme and I also moved the for loop that creates the repositories to the `push_images_to_v2` function since login is irrelevant there so we don't have to deal with both login and creating to the repositories at the same time.

**Comment by mattnowina** [comment]
@mbentley Changes look good. I was still able to pull and push images from Docker Hub to ECR will no issues.

**Comment by mbentley** [comment]
Thanks for verifying!

**Comment by mbentley** [comment]
I was able to get CI to pass after I added another test migration that uses a v2 without login.

**Pull request merged**
