### PR TITLE
Support forced pagination at target repository for retrieving the lis…

### PR DESCRIPTION
**Pull request by madmuffin1**
…t of existing tags (like ECR). Fixes docker/migrator#96

### CODE REVIEW

**Comment by madmuffin1** [comment]
do not merge, grep inside the container does not support PCRE.

**Comment by madmuffin1** [comment]
Updated to not require PCRE.

**Comment by madmuffin1** [comment]
I re-started our migration to ECR this morning and it has been running successfully since and it also successfully skipped all tags that existed at the target. I am migrating ~ 7000 tags and filtering the first 100 really wasn't helping.

**Comment by mbentley** [comment]
Good enough for me :)  Thanks!

**Pull request merged**
